server:
  port: 8080  # 指定网关服务的监听端口为 8080
              # 根据 Nginx 配置文件，所有前端项目的 /api 路径请求将被代理到此端口
spring:
  cloud:
    nacos:
      server-addr: 192.168.187.128:8848
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/addresses/**,/users/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
  application:
    name: gateway
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi